<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-QFI6FBF4" name="restAssured_API.TC02" tests="1" failures="1" timestamp="14 May 2020 02:54:25 GMT" time="2.967" errors="0">
  <testcase name="testWhiteHouseZipAll" time="2.967" classname="restAssured_API.TC02">
    <failure type="java.lang.AssertionError" message="first difference at line#0 col#0: expected [] but was [200]">
      <![CDATA[java.lang.AssertionError: first difference at line#0 col#0: expected [] but was [200]at com.github.writethemfirst.approvals.reporters.ThrowsReporter.mismatch(ThrowsReporter.java:35)at com.github.writethemfirst.approvals.approvers.Approver.verifyImpl(Approver.java:218)at com.github.writethemfirst.approvals.approvers.Approver.verify(Approver.java:203)at com.github.writethemfirst.approvals.Approvals.verify(Approvals.java:50)at restAssured_API.TC02.testWhiteHouseZipAll(TC02.java:17)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- testWhiteHouseZipAll -->
</testsuite> <!-- restAssured_API.TC02 -->
